### ISSUE TITLE
can't use it , it report this errors

### ISSUE THREAD

**Issue by harrisdt15f** [OpherV/gitflow4idea#192] opened 2018-04-02 17:30 UTC
null
java.lang.NullPointerException
	at gitflow.GitflowImpl.run(GitflowImpl.java:62)
	at gitflow.GitflowImpl.initRepo(GitflowImpl.java:106)
	at gitflow.actions.InitRepoAction$1.run(InitRepoAction.java:39)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by OpherV** [comment] 2018-04-02 19:51
Duplicate of #190
Until I release the new version to the jetbrains repo please use the version posted on that thread

**Closed by OpherV** 2018-04-02 19:51 UTC
