### ISSUE TITLE
support of CLion

### ISSUE THREAD

**Issue by samogot** [OpherV/gitflow4idea#62] opened 2015-02-27 08:40 UTC
Can you provide support for CLion - new JetBrains IDE for C/C++, witch on EAP now?

**Comment by OpherV** [comment] 2015-03-01 10:04
Duplicate of #61

**Closed by OpherV** 2015-03-01 10:04 UTC

**Comment by samogot** [comment] 2015-03-04 09:37
clion is still unsupported

**Comment by OpherV** [comment] 2015-03-04 09:44
Looks like clion is still in early EAP, and they [don't have VCS support](https://plugins.jetbrains.com/update/index?pr=&updateId=18802) yet (gitflow4idea relies on git4idea, which in turn relies on the native `com.intellij.modules.vcs` plugin). 

So there's nothing I can do until the platform matures and includes VCS support like the other Jetbrains products. You might want to try and ping their support to see when is that expected to happen.

**Comment by samogot** [comment] 2015-03-04 10:49
i dont know how, but git4idea works fine and installed by default, even if it say that CLoin haven't com.intellij.modules.vcs plugin. looks like git4idea haven't any dependencies now. maybe you can easily remove this native dependency and depend only from git4idea?

**Comment by OpherV** [comment] 2015-03-04 11:43
I am using the vcs in some places - so I'm not sure if that will work out. You're welcome to try and remove it from `plugin.xml` and recompile to see if it all works properly.

If Clion has the vcs plugin as well as git4idea bundled but doesn't list it, it feels like a bug to me and I highly recommend you make Jetbrains aware of it!
