### ISSUE TITLE
The plugin hide my project bar

### ISSUE THREAD

**Issue by mikadev** [OpherV/gitflow4idea#305] opened 2020-05-08 15:30 UTC
Since the latest update when i open multiple Idea projects i don't see the project structure (in left side) please guys if you can take care about this kind of details.

Solution for those have the same bug use the previous version edit the configuration file inside the plugin and update the minimum idea version

/gitflow4idea-0.7.1.zip/gitflow4idea/lib/gitflow4idea-0.7.1.jar/META-INF/plugin.xml

` <idea-version since-build="182.0" until-build="193.*"/>` change to ` <idea-version since-build="182.0" until-build="200.*"/>`

**Comment by OpherV** [comment] 2020-05-08 17:45
duplicate of #301 
A fix is in the works

**Closed by OpherV** 2020-05-08 17:45 UTC
