### ISSUE TITLE
Plugin not compatible with latest IntelliJ version 14.1

### ISSUE THREAD

**Issue by sebastianhenneberg** [OpherV/gitflow4idea#67] opened 2015-03-25 19:59 UTC
The git-flow plugins is not compatible with the latest IntelliJ IDEA version 14.1 (build 141.117). Is there any reason that `until-build` is set to 140.999999 in `plugin.xml`?

**Comment by OpherV** [comment] 2015-03-25 20:00
The only reason is that I still haven't gotten around to it

**Comment by OpherV** [comment] 2015-03-25 20:00
Duplicate of #64

**Closed by OpherV** 2015-03-25 20:00 UTC
