### ISSUE TITLE
NullPointerException while finish release

### ISSUE THREAD

**Issue by cebas** [OpherV/gitflow4idea#153] opened 2017-06-27 15:14 UTC
the command worked fine, but ended with an exception:

error message: "null"

stack trace:

java.lang.NullPointerException
	at gitflow.GitflowConfigUtil.getFeaturePrefix(GitflowConfigUtil.java:58)
	at gitflow.actions.GitflowAction.setup(GitflowAction.java:56)
	at gitflow.actions.GitflowAction.actionPerformed(GitflowAction.java:48)
	at gitflow.actions.FinishReleaseAction.actionPerformed(FinishReleaseAction.java:36)
	at gitflow.actions.FinishReleaseAction$1.onSuccess(FinishReleaseAction.java:107)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:470)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.a(ProgressManagerImpl.java:161)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by OpherV** [comment] 2017-06-27 15:27
Can you reproduce this? If so what are the steps?

**Comment by cebas** [comment] 2017-06-28 04:09
I'm not sure. I have no time to recreate the scenario. Maybe on next release.

**Comment by OpherV** [comment] 2017-10-05 21:13
Probably a duplicate of #157 
Please try with version 0.6.3

**Closed by OpherV** 2017-10-05 21:13 UTC

**Comment by cebas** [comment] 2017-10-05 21:29
I can't find the 0.6.3 jar. In the IDE and in github 0.6.2 is the latest. Where can I get it?

**Comment by OpherV** [comment] 2017-10-05 21:47
In the [releases](https://github.com/OpherV/gitflow4idea/releases) page, or if you a wait a bit it will also be in the Jetbrains repo

**Comment by cebas** [comment] 2017-10-05 21:49
It wasn't there when I checked :)
I'll give it a try

**Comment by cebas** [comment] 2017-11-15 02:10
I've made a couple of releases without problems. It seems to be fixed. Thanks
