### ISSUE TITLE
Incompatible plugin with CLion-1.2

### ISSUE THREAD

**Issue by genieplus** [OpherV/gitflow4idea#94] opened 2015-11-03 10:56 UTC
When I try to add the version 0.4.4 of this plugin to CLion-1.2, an error message is displayed:

Plugin 'Git Flow Integration' is incompatible with this installation.

**Comment by OpherV** [comment] 2015-11-03 10:57
Duplicate of #78

**Closed by OpherV** 2015-11-03 10:57 UTC
