### ISSUE TITLE
Missing UI on the plugin button

### ISSUE THREAD

**Issue by dekelev** [OpherV/gitflow4idea#267] opened 2019-12-17 18:44 UTC
* **I'm submitting a ...**
  - [ x] bug report

* **What is the current behavior?**

Status bar doesn't show any Icon or text for the GitFlow plugin button. just black space, which is still clickable and opens the plugin menu.

* **Is this a bug?**

Yes, it's a bug. I've updated the IDE to v2019.3 build #IU-193.5233.102 and now I'm getting the following error on Git Flow Integration plugin v0.7.1 when loading the IDE:

com.intellij.diagnostic.PluginException: Icon cannot be found in 'AllIcons.Vcs.', action 'class gitflow.actions.TrackFeatureAction' [Plugin: Gitflow] at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:378) at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:373) at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.access$000(ActionManagerImpl.java:70) at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$1.compute(ActionManagerImpl.java:271) at com.intellij.openapi.util.IconLoader$LazyIcon.getOrComputeIcon(IconLoader.java:1074) at com.intellij.openapi.util.IconLoader$LazyIcon.getIconHeight(IconLoader.java:1063) at com.intellij.openapi.keymap.impl.ui.ActionsTree.getEvenIcon(ActionsTree.java:426) at com.intellij.openapi.keymap.impl.ui.ActionsTree$KeymapsRenderer.customizeCellRenderer(ActionsTree.java:591) at com.intellij.ui.ColoredTreeCellRenderer.rendererComponentInner(ColoredTreeCellRenderer.java:117) at com.intellij.ui.ColoredTreeCellRenderer.getTreeCellRendererComponent(ColoredTreeCellRenderer.java:52) at com.intellij.ui.tree.ui.DefaultTreeUI.getRenderer(DefaultTreeUI.java:135) at com.intellij.ui.tree.ui.DefaultTreeUI.access$500(DefaultTreeUI.java:39) at com.intellij.ui.tree.ui.DefaultTreeUI$1.getNodeDimensions(DefaultTreeUI.java:326) at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:493) at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344) at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1465) at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1272) at java.desktop/javax.swing.tree.VariableHeightLayoutCache.ensurePathIsExpanded(VariableHeightLayoutCache.java:967) at java.desktop/javax.swing.tree.VariableHeightLayoutCache.setExpandedState(VariableHeightLayoutCache.java:181) at java.desktop/javax.swing.plaf.basic.BasicTreeUI.updateExpandedDescendants(BasicTreeUI.java:1975) at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeExpanded(BasicTreeUI.java:4212) at java.desktop/javax.swing.JTree.fireTreeExpanded(JTree.java:2801) at java.desktop/javax.swing.JTree.setExpandedState(JTree.java:3702) at java.desktop/javax.swing.JTree.expandPath(JTree.java:2244) at com.intellij.util.ui.tree.TreeUtil.expandPathWithDebug(TreeUtil.java:1300) at com.intellij.util.ui.tree.TreeUtil.lambda$promiseMakeVisible$32(TreeUtil.java:1458) at com.intellij.util.ui.tree.TreeUtil.visitModel(TreeUtil.java:1710) at com.intellij.util.ui.tree.TreeUtil.lambda$promiseVisit$41(TreeUtil.java:1675) at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2413) at com.intellij.util.ui.tree.TreeUtil.promiseVisit(TreeUtil.java:1675) at com.intellij.util.ui.tree.TreeUtil.promiseMakeVisible(TreeUtil.java:1446) at com.intellij.util.ui.tree.TreeUtil.promiseExpand(TreeUtil.java:930) at com.intellij.util.ui.tree.TreeUtil.promiseExpandAll(TreeUtil.java:894) at com.intellij.util.ui.tree.TreeUtil.expandAll(TreeUtil.java:870) at com.intellij.openapi.keymap.impl.ui.KeymapPanel$9.lambda$filter$0(KeymapPanel.java:393) at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231) at com.intellij.util.Alarm$Request.runSafely(Alarm.java:371) at com.intellij.util.Alarm$Request.run(Alarm.java:358) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:217) at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309) at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441) at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424) at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407) at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746) at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906) at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779) at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422) at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:687) at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421) at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117) at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) at java.desktop/java.awt.Dialog.show(Dialog.java:1063) at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:708) at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:433) at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1698) at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1657) at com.intellij.openapi.options.newEditor.SettingsDialog.lambda$show$0(SettingsDialog.java:86) at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83) at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:149) at com.intellij.openapi.options.newEditor.SettingsDialog.show(SettingsDialog.java:86) at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:84) at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:54) at com.intellij.ui.mac.MacOSApplicationProvider$Worker.lambda$null$1(MacOSApplicationProvider.java:66) at com.intellij.ui.mac.MacOSApplicationProvider$Worker.lambda$submit$7(MacOSApplicationProvider.java:162) at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83) at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:68) at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441) at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424) at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407) at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746) at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906) at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779) at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422) at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698) at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421) at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

* **What is the expected behavior?**

Status bar should show icon or/and text on the button that opens the plugin menu.

* **What is the motivation / use case for changing the behavior?**

UI is missing

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.1
  - Gitflow version: 1.12.3 (AVH Edition)
  
IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 28, 2019
Licensed to Lusha / Dekel Barzilay
Subscription is active until June 4, 2020
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: debugger.watches.in.variables=false, js.debugger.webconsole=false
Non-Bundled Plugins: Gitflow, Pythonid, com.atlassian.bitbucket.references, com.deadlock.scsyntax, com.intellij.apacheConfig, com.jetbrains.php, com.jetbrains.upsource, cucumber-javascript, mobi.hsz.idea.gitignore, net.seesharpsoft.intellij.plugins.csv, org.intellij.scala

**Comment by OpherV** [comment] 2019-12-17 18:47
duplicate of #266

**Closed by OpherV** 2019-12-17 18:47 UTC
