### ISSUE TITLE
NullPointerException while opening task in idea 2017.2.2

### ISSUE THREAD

**Issue by Tamrael** [OpherV/gitflow4idea#168] opened 2017-08-29 13:51 UTC
in version 0.6.2 while working with 2 projects opened at the same time sometimes on of the projects git flow integration is broken. you can close the project and reopen it again to temporarily get the task open dialog to work again but the bug keeps reappearing after a time.

Stacktrace:
`null
java.lang.NullPointerException
	at gitflow.ui.GitflowTaskDialogPanelProvider.getOpenTaskPanel(GitflowTaskDialogPanelProvider.java:26)
	at com.intellij.tasks.ui.TaskDialogPanelProvider.lambda$getOpenTaskPanels$0(TaskDialogPanelProvider.java:39)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1913)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1862)
	at com.intellij.tasks.ui.TaskDialogPanelProvider.getOpenTaskPanels(TaskDialogPanelProvider.java:38)
	at com.intellij.tasks.actions.OpenTaskDialog.<init>(OpenTaskDialog.java:103)
	at com.intellij.tasks.actions.GotoTaskAction.lambda$showOpenTaskDialog$0(GotoTaskAction.java:113)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by OpherV** [comment] 2017-08-29 13:59
duplicate of #157

**Closed by OpherV** 2017-08-29 13:59 UTC
