### ISSUE TITLE
Multi Repository Support

### ISSUE THREAD

**Issue by YanickFrehner** [OpherV/gitflow4idea#175] opened 2017-10-11 11:46 UTC
Please add Multi Git Repository Support like the standard Git implementation in PHPStorm already got one

**Comment by OpherV** [comment] 2017-10-11 14:31
What do you mean? Multi repo support already exists.

**Comment by YanickFrehner** [comment] 2017-10-11 15:21
Sorry for the Short description.
What I realy mean is that i would realy appreciate if it is possible to keep the multiple repositorys in sync, Like it is possible in normal Git implementation of PHP storm.
For example creating a new feature branch for all the repositorys in the Project with one klick, when the repositorys are already on the same branch

**Comment by OpherV** [comment] 2017-10-12 15:40
Duplicate of #166

**Closed by OpherV** 2017-10-12 15:40 UTC
