### ISSUE TITLE
Defect and Feature Request: Renaming a feature branch dissociates it from its changelist

### ISSUE THREAD

**Issue by morsedl** [OpherV/gitflow4idea#224] opened 2019-02-21 18:05 UTC
**Issue**

If you rename a feature branch --- either at the command line or with the VCS -> Git -> Branches -> Rename menu option in the IDE --- it becomes disassociated with its changelist.

For example, I can rename a feature branch from "feature/my-feature-1" to "feature/my-feature-1-with-different-name" (CLI or in IDE), and all is well. Let's call the changelist associated with this feature branch "my-feature-1". Of course, however, from time to time I need to make a different changelist active, and gitflow4idea conveniently also automatically switches to (or creates) the target branch associated with that changelist. For this example, let's say this other changelist is called "my-feature-2" and its associated feature branch is "feature/my-feature-2".

Switching from changelist "my-feature-1" to "my-feature-2" works fine, thus still no problems so far. *However*, as soon as I switch back from changelist "my-feature-2" to "my-feature-1", gitflow4idea tries to checkout "feature/my-feature-1" (instead of "feature/my-feature-1-with-different-name"), does not find it, and so creates a new, empty branch called "feature/my-feature-1", which is obviously not the desired behavior.

**Request (Summary)**

1. Provide an option to enable preventing the problem in the first place.
2. Provide an option to allow the user to be warned before the plugin creates an unwanted, empty branch.
3. Provide an option to help correct the problem if it has occurred.
4. Routinely check if the presently-active branch matches that associated with the presently-active changelist and, if not, warn the user, with an option to then correct the problem (item 3).

**Request (Details)**

1. Add an option in the gitflow4idea UI to rename a branch that prevents this problem (related: see Technical Details, next section).
2. Add a (boolean) setting that allows users to specify if they want to be warned before creating a new branch under the following conditions:
    * The user is making a different changelist active (i.e., is switching changelists)
    * The target changelist has a feature branch associated with it
    * This associated feature branch does not exist
3. As a part of the interaction for warning users (item 2), provide a list of branches and allow the users to pick the correct branch with which to re-associated the changelist with a branch.
    * It's probably wise to limit the list of branches to those following under the feature-branch-prefix (e.g., feature/, topic/, etc.) specified in .git/config.
    * It's probably wise regarding the list of branches to list all those branches already associated with a changelist last, and emphasize this fact (e.g., perhaps using an italic font, using a different font color, such as grey, and even under a separate a dialog-box section, named, for example, "Already in use").
    * If there are any issues with having a feature branch associated with more than one changelist (e.g., the user selects an "Already in use" branch), either warn the user of the possible consequences of doing so, or, if such issues are serious enough, disallow using already-in-use changelists altogether.
    * It's probably also helpful to further divide the list of available feature branches such that matches "similar" to the existing association are shown first, then all others (e.g., in the example in the previous section, very simple pattern matching, e.g., start of strings match, would detect that "feature/my-feature-1-with-different-name" is a good candidate for what was "feature/my-feature-1").
    * An even more helpful implementation of the previous would be to have some sort of criteria and algorithm that determines if there is a clear best candidate, and as a first step prompts the user to use it, before presenting the list of (feature) branches (e.g., "Branch 'feature/my-feature-1' no longer exists. A different branch, 'feature/my-feature-1-with-different-name', is not associated with any changelist and is named similarly. Would you like to associated this branch with this changelist?: Yes, No, Select Different Branch, Cancel).
4. Whenever possible and as often as needed, warn the user if the active feature branch does not match what gitflow4idea thinks it should be, as well as provide an option to correct this (i.e., an option that redirects him or her to the functionality in the previous item 3). If gitflow4idea can be notified when the IDE refreshes / resyncs with native git, that likely would be an ideal time to check if the branch name is different than expected, and such an implementation would require very little additional processing overhead. (This of course might not be possible or there may be other, preferable solutions.)

**Technical Details**

This issue is rooted in the fact that, when a git branch is renamed (CLI or in IDE), the appropriate ```<branch>``` entry (within the appropriate ```<task>``` entry) in the file .idea/workspace.xml is not updated.

For the example in the first section, then, the following entry:

```<branch name="feature/my-feature-1" repository="$PROJECT_DIR$" />```

should have been updated to the following when the branch was renamed:

```<branch name="feature/my-feature-1-with-different-name" repository="$PROJECT_DIR$" />```

(Indeed, making such a correction manually is trivial and is how I fixed things when I first encountered this problem.)

For CLI, updating this ```<branch>``` entry likely would be accomplished using git hooks, and, as such, is probably out of scope of what gitflow4idea cares to handle.

For the Jetbrains' IDEs, updating the branch entry ought be trivial, at least in the case of Request item 1 (above). For the "native" IDE option to rename a branch (i.e., menu option VCS -> Git -> Branches -> Rename), the ease of implementing a solution of course will depended whether Jetbrains plugin authors can either create hooks to that menu option (or perhaps register callbacks with it).

**Context**  

- Gitflow4idea version: 0.6.6
- Gitflow version: 1.9.1 (AVH Edition)
- PyCharm version:  
~~~~
PyCharm 2018.2.4 (Professional Edition)
Build #PY-182.4505.26, built on September 19, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-38-generic
~~~~

**Comment by OpherV** [comment] 2019-02-22 15:28
Thanks for the very detailed report @morsedl 
I'll have a look at this when I get the chance

**Comment by OpherV** [comment] 2019-09-05 09:59
@morsedl I assume you're talking about changelists created with the new task dialog?

**Comment by morsedl** [comment] 2019-09-09 20:30
@OpherV Yes, that is correct. SVN supports changelists, but [Git does not][1]. So far as I am aware, changelists for Git Repos in Jetbrains IDEs is a function provided soley by the IDE and not really accessible outside of the IDE.

[1]: https://stackoverflow.com/questions/10606809/git-equivalence-of-svn-changelist

**Comment by OpherV** [comment] 2019-09-10 12:39
@morsedl So to summarize as I understand the issue is 

1. Git branches and changelists are created for new task. The branches are are properly associated with the changelist
2. When a branch is renamed, it loses association with the original changelist

Yes?

**Comment by morsedl** [comment] 2019-09-15 02:11
@OpherV : Correct. This can of course happen outside of the IDE, with say CLI git or git-kraken or whatever. The plugin won't know of this of course until after the fact, hence the need for some sort of detection and correction within the plugin. But even down within the IDE, as I described, the disassociations still happens. Probably because the steps to renaming a branch aren't hooked up with the plugin. So if those menu actions have hooks or one can insert an inverse dependency, your plugin could know about the branch renaming as it's happening and ensue the associations is properly maintained. More likely I imagine, however, is no such hooks / possibility for reverse injection exists. So, that's where the same detection and correction mechanisms you might write for handling the renaming of the branch outside of the IDE might also become the only way of dealing with a branch renaming even if the use is doing so right within the IDE. Hope this helps.

**Comment by OpherV** [comment] 2019-09-15 07:44
Note that in my summarized description I haven't mentioned git flow at all. 

While I completely agree that it would be nice to have a feature that keeps branches aligned even after rename, it sounds out of scope for this plugin and more like something IntelliJ could implement generally in their git plugin.

My suggestion would be essentially cutting and pasting the important bits of this discussion to the proper IntelliJ bug reporting channels

Closing for now

**Closed by OpherV** 2019-09-15 07:44 UTC
