### ISSUE TITLE
After updating WebStorm to version 2021.2, the plugin broke

### ISSUE THREAD

**Issue by LDWork** [OpherV/gitflow4idea#334] opened 2021-07-28 07:50 UTC
After updating WebStorm to version 2021.2, the plugin broke

`Plugin 'Git Flow Integration' (version '0.7.6') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is WS-212.4746.80`

**Comment by desmond27** [comment] 2021-07-29 13:36
Also does not work with IDEA 2021.2

`Plugin 'Git Flow Integration' (version '0.7.6') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is IU-212.4746.92`

**Comment by OpherV** [comment] 2021-07-30 11:22
Duplicate of #332

**Closed by OpherV** 2021-07-30 11:22 UTC
