### ISSUE TITLE
Unsupported Gitflow version after IDE updated to 3.6

### ISSUE THREAD

**Issue by bmalex88** [OpherV/gitflow4idea#281] opened 2020-02-27 16:52 UTC
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**

When I open Android Studio, the bottom bar says _Unsupported Gitflow version_. The version of my _gitflow_ extension is **1.12.3 (AVH edition)** so it should not say that

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open Android Studio and get the latest update
2. Restart

* **What is the expected behavior?**

Should detect the AVH edition

* **What is the motivation / use case for changing the behavior?**

Poor coding when detecting the version of _git fow_

* **Please tell me about your environment:**
  
  - Gitflow4idea version: *0.7.1*
  - Gitflow version: 1.12.3 (AVH edition)
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
Android Studio 3.6
Build #AI-192.7142.36.36.6200805, built on February 12, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 8.1 6.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.new.welcome.screen.force=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: CheckStyle-IDEA, com.dengzii.plugin.adb, Gitflow, org.intellij.plugins.markdown, com.chrisrm.idea.MaterialThemeUI
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by blundell** [comment] 2020-03-09 09:14
Also occurs with:
```
$ git flow version
1.11.0 (AVH Edition)
```

**Comment by blundell** [comment] 2020-03-09 11:06
I forked the repo here:

And added this test:

```
    @Test
    public void isSupportedVersion() throws VcsException {
        Gitflow mockGitflow = mock(Gitflow.class);
        Project mockProject = mock(Project.class);
        GitflowVersionTester tester = new GitflowVersionTester(mockGitflow, mockProject);

        GitCommandResult mockGitCommandResult = mock(GitCommandResult.class);
        when(mockGitflow.version(mockProject)).thenReturn(mockGitCommandResult);
        when(mockGitCommandResult.getOutputOrThrow()).thenReturn("1.11.0 (AVH Edition)");

        assertTrue(tester.isSupportedVersion());
    }
```

**Which passes**.

So at a glance this makes me think the problem is elsewhere, perhaps the plugin needs updating as its using deprecated IntelliJ plugin methods. Perhaps this variable is not null `myGitflowWidget`, so it is giving the error message incorrectly:
![image](https://user-images.githubusercontent.com/655860/76207392-9dc47080-61f5-11ea-8b80-22e48a3b9652.png)

**Comment by blundell** [comment] 2020-03-09 14:07
Is the fix as simple as:

```java
//make sure to not reinitialize the widget if it's already present
            if (GitflowVersionTester.forProject(myProject).isSupportedVersion()) {
                if(myGitflowWidget == null) {
                   myGitflowWidget = new GitflowWidget(myProject);
                }
                widgetToAdd = (StatusBarWidget) myGitflowWidget;
            } else {
                widgetToAdd = new GitflowUnsupportedVersionWidget(myProject);
            }
```

**Comment by blundell** [comment] 2020-03-09 15:06
Oh brilliant, closing and re-opening my AndroidStudio fixed it (for me)..... (in the meantime I downloaded the latest IntelliJ, don't know if that had anything to do with it).

**Comment by blundell** [comment] 2020-04-01 14:23
same issue as: https://github.com/OpherV/gitflow4idea/issues/277

**Comment by OpherV** [comment] 2020-05-03 18:54
Did some refactoring, please test with 0.7.2 and reopen if necessary

**Closed by OpherV** 2020-05-03 18:54 UTC
