### ISSUE TITLE
Plugin not available in PhpStorm 9.5

### ISSUE THREAD

**Issue by mickadoo** [OpherV/gitflow4idea#90] opened 2015-10-27 10:01 UTC
I tried to install the plugin after upgrading to the latest PhpStorm but it looks [here](https://plugins.jetbrains.com/plugin/7315?pr=phpStorm) like it is not compatible with the build I have (143.434).

**Comment by OpherV** [comment] 2015-10-28 08:49
Duplicate of #78

**Closed by OpherV** 2015-10-28 08:49 UTC
