### ISSUE TITLE
Issues during git flow init

### ISSUE THREAD

**Issue by ciscorucinski** [OpherV/gitflow4idea#140] opened 2017-04-19 14:09 UTC
At first I was receiving this message...

    23:49:45.761: [ChroMATERIAL Plugin] git -c core.quotepath=false flow init
    git: 'flow' is not a git command. See 'git --help'.
    Did you mean one of these?
        reflog
        show
    
... and I seemed to have fixed it by changing the IntelliJ IDEA git executable to...

    C:\Users\Christopher\AppData\Local\GitHub\PortableGit_f02737a78695063deace08e96d5042710d3e32db\cmd\git.exe

... this references the newly downloaded `Git for Windows v2` `git.exe` executable which includes `Git Flow`. **However, while this has fixed the above issue, I now get the following issue that I cannot seem to overcome**...

    22:52:20.689: [ChroMATERIAL Plugin] git -c core.quotepath=false flow init
    Which branch should be used for bringing forth production releases?
       - master
    22:52:38.817: master
    ' does not exist.
    Branch name for production releases: [master]

**Comment by ciscorucinski** [comment] 2017-04-21 15:49
In the IntelliJ IDEA terminal I manually did the init process and everything worked fine.

    git flow init

...and go through the step by step guide. I didn't get the `' does not exist` issue then, and the drop-down menu in the lower-right was initialized correctly then.

It isn't ideal, as the drop-down menu should have worked, so I won't close this issue.

**What is the reason to do the following?**

    git -c core.quotepath=false flow init

_Rather than the simpler_

    git flow init

**Comment by OpherV** [comment] 2017-04-22 19:21
There's some known issue with the git flow bundled with the windows git - I haven't had the chance to get to the bottom of it just yet - but I will. With the AVH version of git flow it works fine.

The `-c core.quotepath=false` is something added by the Intellij git4idea plugin which gitflow4idea relies on. I don't believe this is the source is the issue though.

**Comment by OpherV** [comment] 2017-04-22 19:22
Closing as a duplicate of #125

**Closed by OpherV** 2017-04-22 19:22 UTC
