### ISSUE TITLE
IDE Error Occured, Exception in Plugin 

### ISSUE THREAD

**Issue by Ajio1stJb** [OpherV/gitflow4idea#243] opened 2019-08-01 05:28 UTC
Submitting a bug report

  ~~~~
 java.lang.NullPointerException
    at gitflow.GitflowBranchUtilManager.getBranchUtil(GitflowBranchUtilManager.java:21)
	at gitflow.ui.GitflowTaskDialogPanelProvider.getOpenTaskPanel(GitflowTaskDialogPanelProvider.java:25)
	at com.intellij.tasks.ui.TaskDialogPanelProvider.getOpenTaskPanel(TaskDialogPanelProvider.java:38)
	at com.intellij.tasks.ui.TaskDialogPanelProvider.lambda$getOpenTaskPanels$0(TaskDialogPanelProvider.java:24)
	at com.intellij.util.containers.ContainerUtilRt.mapNotNull(ContainerUtilRt.java:378)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1973)
	at com.intellij.tasks.ui.TaskDialogPanelProvider.getOpenTaskPanels(TaskDialogPanelProvider.java:23)
	at com.intellij.tasks.actions.OpenTaskDialog.<init>(OpenTaskDialog.java:96)
	at com.intellij.tasks.actions.GotoTaskAction.lambda$showOpenTaskDialog$0(GotoTaskAction.java:115)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

  ~~~~

  
  - Gitflow4idea version: 0.6.8
  - Gitflow version: run in terminal `> 1.12.3 (AVH Edition)
  
  ~~~~
    IntelliJ IDEA 2019.1.4 (Ultimate Edition)
    Build #IU-191.8026.42, built on July 30, 2019
    JRE: 1.8.0_212-release-1586-b4 amd64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  ~~~~

**Comment by OpherV** [comment] 2019-08-04 07:06
Please provide details on how to reproduce

**Comment by EHLOVader** [comment] 2019-08-08 14:29
I have gotten this error ever since switching to 2019 and it appears to happen when you go to action (command+shift+p) and try to use any of the gitflow commands. 

Typing feature, hotfix, or release will do it for me.

**Comment by bmwsedee** [comment] 2019-08-09 05:32
This should be fixed with the same fix as for https://github.com/OpherV/gitflow4idea/issues/235, so I guess we'll just have to wait for a new version of the plugin to be released

**Comment by OpherV** [comment] 2019-08-22 19:08
Version 0.6.9 is now on the Jetbrains Repo

**Closed by OpherV** 2019-08-22 19:08 UTC
