### ISSUE TITLE
Error the git flow init with the non-default configuration

### ISSUE THREAD

**Issue by denisbondar** [OpherV/gitflow4idea#141] opened 2017-04-22 09:07 UTC
I have a problem with initialization with the option "**Use non-default configuration**".

![image](https://cloud.githubusercontent.com/assets/5622389/25303024/b167089e-2753-11e7-9c90-735a49cfb213.png)

In the git console I see the error:
```
11:56:24.627: [project] git -c core.quotepath=false flow init
Which branch should be used for bringing forth production releases?
   - dev
   - master
11:56:26.524: master
' does not exist.
```

PHPStorm 2017.1.2, Git Flow Integration v0.5.1

**Comment by OpherV** [comment] 2017-04-22 19:13
Thanks for the submission!
Which git flow version are you using? AVH version or vanilla version?

**Comment by OpherV** [comment] 2017-04-22 19:22
Closing as duplicate of #125

**Closed by OpherV** 2017-04-22 19:22 UTC

**Comment by denisbondar** [comment] 2017-04-23 13:40
1.9.1 (AVH Edition)
